name: portfolio-site-ci

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    stephs:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-site:latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
